### ISSUE TITLE
How to compile for aarch64

### ISSUE THREAD

**Issue by ykhandler** [satishp7/squashfs-tool-android#1]
Hi, can you explain how to compile this binary for aarch64? Thanks.

**Comment by satishp7** [comment]
@ykhandler - I have validate this on 64-bit platform only ([Hikey](https://www.96boards.org/product/hikey/)) 
. So it should work as is. 
If at all you would like to build only aarch64 version then add following line to Android.mk
LOCAL_MULTILIB := 64

**Comment by ykhandler** [comment]
I'm using linux ubuntu to compile it, with android cross compiler and it result on some errors. I'm trying to compile it for my Samsung S7 Edge cellphone. 
ABIs: arm64-v8a, armeabi-v7a, armeabi
CPU Cores: 8
CPU Bit: 64-Bit

can you share a prebuild binary, so i can test it if it is also working?  It looks like the Hikey have a similiar platform with my S7 edge.

**Comment by satishp7** [comment]
I do not have prebuilt image backed up with me. But I can help you to debug the errors you are getting.

Could you paste the error logs >

**Comment by ykhandler** [comment]
Here are the error, please help me:
aarch64-linux-android-gcc -O2  -I. -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DCOMP_DEFAULT=\"gzip\" -Wall -DGZIP_SUPPORT -DZSTD_SUPPORT -DXATTR_SUPPORT -DXATTR_DEFAULT   -c -o mksquashfs.o mksquashfs.c
mksquashfs.c:987:29: error: called object type 'unsigned int' is not a function
      or function pointer
                unsigned int major = major(buf->st_rdev);
                                     ~~~~~^
mksquashfs.c:988:29: error: called object type 'unsigned int' is not a function
      or function pointer
                unsigned int minor = minor(buf->st_rdev);
                                     ~~~~~^
mksquashfs.c:1011:29: error: called object type 'unsigned int' is not a function
      or function pointer
                unsigned int major = major(buf->st_rdev);
                                     ~~~~~^
mksquashfs.c:1012:29: error: called object type 'unsigned int' is not a function
      or function pointer
                unsigned int minor = minor(buf->st_rdev);
                                     ~~~~~^
mksquashfs.c:3527:17: warning: implicit declaration of function 'makedev' is
      invalid in C99 [-Wimplicit-function-declaration]
                buf.st_rdev = makedev(pseudo_ent->dev->major,
                              ^
mksquashfs.c:4404:29: error: use of undeclared identifier 'FNM_EXTMATCH'
                                FNM_PATHNAME|FNM_PERIOD|FNM_EXTMATCH) == 0;
                                                        ^
1 warning and 5 errors generated.
make: *** [mksquashfs.o] Error 1

**Comment by satishp7** [comment]
It is recommended to clone this repo inside external/ dir and compile using normal Android build setup. As it might look for headerfile which is present on Android include dir list.
Could you try that out once ? Will try on my end as well

**Comment by ykhandler** [comment]
Thank you for your help. I've manage to get the binary and the library to run it. I'll close the issue.
